CLASS /dmo/bp_booking_u21 DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF /dmo/i_travel_u21 .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS /dmo/bp_booking_u21 IMPLEMENTATION.
ENDCLASS.
